# Generated by Django 2.1.4 on 2018-12-27 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='twit',
            name='title',
            field=models.CharField(default='title', max_length=100),
        ),
    ]
